# Generated by Django 2.0.2 on 2019-11-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
