# Generated by Django 2.0.2 on 2019-11-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogger', '0004_remove_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsite',
            old_name='date_publish',
            new_name='date',
        ),
        migrations.AddField(
            model_name='blogsite',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
