# Generated by Django 2.0.2 on 2019-11-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_auto_20191114_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsite',
            name='body',
        ),
        migrations.AddField(
            model_name='blogsite',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blogsite',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogsite',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
