# Generated by Django 2.0.2 on 2019-11-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0008_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsite',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
