# Generated by Django 2.0.2 on 2019-11-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0014_auto_20191128_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default.png', null=True, upload_to='images/'),
        ),
    ]
