# Generated by Django 2.0.2 on 2019-11-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0016_auto_20191129_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='pic',
        ),
    ]
