# Generated by Django 2.0.2 on 2019-11-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0017_auto_20191129_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='blogger/images/default.png', null=True, upload_to='images'),
        ),
    ]
