# Generated by Django 2.0.2 on 2019-11-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0021_auto_20191129_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='profile',
        ),
    ]
