# Generated by Django 2.0.2 on 2019-12-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0022_auto_20191129_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='static/images/default.png', null=True, upload_to='images'),
        ),
    ]
